# Generated by Django 4.1.3 on 2022-11-29 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0001_initial'),
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Время удаления')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TechMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Время удаления')),
                ('description', models.TextField(verbose_name='Описание')),
                ('output', models.FloatField(verbose_name='Суммарный выход продукта')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Розничная цена')),
                ('bookmark_rate', models.PositiveSmallIntegerField(verbose_name='Норма закладки (порций)')),
                ('dish', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='menu.dish', verbose_name='Блюдо')),
                ('measure_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='techmaps', to='warehouse.measureunit', verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Тех.карта',
                'verbose_name_plural': 'Тех.карты',
            },
        ),
        migrations.CreateModel(
            name='TechMapPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Время удаления')),
                ('image_url', models.URLField(verbose_name='Изображение накладной')),
                ('tech_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='menu.techmap', verbose_name='Тех.карта')),
            ],
            options={
                'verbose_name': 'Фото тех.карты',
                'verbose_name_plural': 'Фото тех.карты',
            },
        ),
        migrations.CreateModel(
            name='Modifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Время удаления')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifiers', to='menu.dish', verbose_name='Блюдо')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Время удаления')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='place.place', verbose_name='Ресторан')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Время удаления')),
                ('amount', models.FloatField(default=1, verbose_name='Количество')),
                ('done_weight', models.FloatField(verbose_name='Выход готового продукта')),
                ('uncritical', models.BooleanField(default=False, verbose_name='Не критичный для приготовления')),
                ('dish', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredients', to='menu.dish', verbose_name='Блюдо')),
                ('measure_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingredients', to='warehouse.measureunit', verbose_name='Единица измерения')),
                ('modifier', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredients', to='menu.modifier', verbose_name='Модификатор')),
                ('nomenclature_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingredients', to='warehouse.nomenclaturegroup', verbose_name='Номенклатурная группа')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
            },
        ),
        migrations.AddField(
            model_name='dish',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='menu.menu', verbose_name='Меню'),
        ),
    ]
